version: '3.8'

services:
  db:
    image: mysql:8.0 # 또는 최신 안정 버전
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - "${DB_PORT}:3306"

  auth-server:
    environment:
        DB_HOST: ${DB_HOST}
        DB_USER: ${DB_USER}
        DB_PASSWORD: ${DB_PASSWORD}
        DB_NAME: ${DB_NAME}
    build:
      context: ./auth-server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db