version: '3.8'

services:
  db:
    image: mysql:8.0 # 또는 최신 안정 버전
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  auth-server:
    build:
      context: ./auth-server
      dockerfile: Dockerfile
    volumes:
      - ./auth-server/src/swagger/Swagger.yaml:/usr/src/app/src/swagger/Swagger.yaml
    environment:
      DB_HOST: db
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    ports:
      - "8000:8000"
    depends_on:
      - db

  data-server:
    build:
      context: ./data-server
      dockerfile: Dockerfile
    volumes:
      - ./swagger.yaml:/usr/src/app/swagger.yaml 
    environment:
      DB_HOST: db
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    ports:
      - "8001:8001"
    depends_on:
      - db
