openapi: 3.0.0
info:
  title: API Documentation
  version: 1.0.0
  description: Documentation for the Budget and Supply API
servers:
  - url: http://localhost:8001
    description: Local server

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Budget:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        amount:
          type: number
    PostBudget:
      type: object
      properties:
        name:
          type: string
        amount:
          type: number
    Supply:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        price:
          type: integer
    PostSupply:
      type: object
      properties:
        name:
          type: string
        price:
          type: integer

security:
  - bearerAuth: []

paths:
  /api/data/budgets:
    get:
      summary: Get all budgets
      tags: 
        - Budgets
      security:
        - bearerAuth: []
      responses:
        200:
          description: A list of budgets
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Budget'
        500:
          description: Error fetching budgets
    post:
      summary: Create a new budget
      tags: 
        - Budgets
      security:
        - bearerAuth: []
      requestBody:
        description: Budget object to create
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostBudget'
      responses:
        201:
          description: New budget created successfully
        500:
          description: Error creating budget

  /api/data/budgets/{id}:
    get:
      summary: Get a budget by ID
      tags: 
        - Budgets
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Budget found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Budget'
        404:
          description: Budget not found
        500:
          description: Error fetching budget
    put:
      summary: Update a budget by ID
      tags: 
        - Budgets
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        description: Budget object to update
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Budget'
      responses:
        200:
          description: Budget updated successfully
        500:
          description: Error updating budget
    delete:
      summary: Delete a budget by ID
      tags: 
        - Budgets
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Budget deleted successfully
        404:
          description: Budget not found
        500:
          description: Error deleting budget

  /api/data/supplies:
    get:
      summary: Get all supplies
      tags: 
        - Supplies
      security:
        - bearerAuth: []
      responses:
        200:
          description: A list of supplies
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Supply'
        500:
          description: Error fetching supplies
    post:
      summary: Create a new supply
      tags: 
        - Supplies
      security:
        - bearerAuth: []
      requestBody:
        description: Supply object to create
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostSupply'
      responses:
        201:
          description: New supply created successfully
        500:
          description: Error creating supply

  /api/data/supplies/{id}:
    get:
      summary: Get a supply by ID
      tags: 
        - Supplies
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Supply found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Supply'
        404:
          description: Supply not found
        500:
          description: Error fetching supply
    put:
      summary: Update a supply by ID
      tags: 
        - Supplies
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        description: Supply object to update
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Supply'
      responses:
        200:
          description: Supply updated successfully
        500:
          description: Error updating supply
    delete:
      summary: Delete a supply by ID
      tags: 
        - Supplies
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Supply deleted successfully
        404:
          description: Supply not found
        500:
          description: Error deleting supply
