openapi: 3.0.0
info:
  title: Member API Documentation
  version: 1.0.0
  description: Documentation for the Member API
servers:
  - url: http://localhost:8000
    description: Local server

components:
  schemas:
    PostMember:
      type: object
      properties:
        id:
          type: string
        password:
          type: string
        role:
          type: number
          format: float
        name:
          type: string
      required:
        - id
        - password
        - role
        - name
    GetMember:
      type: object
      properties:
        id:
          type: string
        role:
          type: string
        name:
          type: string
    Login:
      type: object
      properties:
        id:
          type: string
        password:
          type: string
      required:
        - id
        - password
    Session:
      type: object
      properties:
        sessionId:
          type: string
        accessToken:
          type: string

paths:
  /api/auth/member:
    get:
      summary: Get all members
      tags: 
        - Members
      security:
        - bearerAuth: []
      responses:
        200:
          description: A list of members
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/GetMember'
        500:
          description: Internal server error
    post:
      summary: Create a new member
      tags: 
        - Members
      security:
        - bearerAuth: []
      requestBody:
        description: Member object to create
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostMember'
      responses:
        201:
          description: New member created successfully
        400:
          description: Invalid request body
        409:
          description: Duplicate ID
        500:
          description: Internal server error

  /api/auth/member/{id}:
    get:
      summary: Get a member by ID
      tags: 
        - Members
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: Member found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetMember'
        404:
          description: Member not found
        500:
          description: Internal server error

  /api/auth/login:
    post:
      summary: Login user
      tags:
        - Auth
      requestBody:
        description: User credentials for login
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Login'
      responses:
        200:
          description: User logged in successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Session'
        401:
          description: Unauthorized
        500:
          description: Internal server error
