openapi: 3.0.0
info:
  title: API Documentation
  version: 1.0.0
  description: 인증 및 데이터 관리 API

servers:
  - url: http://localhost:8000
  
paths:
  /api/auth/login:
    post:
      summary: 사용자 로그인
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                  description: 사용자 ID
                password:
                  type: string
                  description: 사용자 비밀번호
      responses:
        '200':
          description: 성공적으로 로그인
          content:
            application/json:
              schema:
                type: object
                properties:
                  sessionId:
                    type: string
                    description: 세션 ID
                  accessToken:
                    type: string
                    description: 액세스 토큰
        '401':
          description: 인증 실패
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "비밀번호가 일치하지 않습니다."

  /api/auth/member:
    post:
      summary: 새로운 회원 등록
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                  description: 사용자 ID
                password:
                  type: string
                  description: 사용자 비밀번호
                role:
                  type: number
                  description: 사용자 역할
                name:
                  type: string
                  description: 사용자 이름
      responses:
        '201':
          description: 회원이 성공적으로 등록됨
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
        '400':
          description: 잘못된 요청
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "ID가 필요합니다."
        '409':
          description: 중복 ID 오류
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string